---
- name: Install requirement packet and login
  hosts: cloudmaster
  roles:
    - { role: env-init }
  tags: env-init

- name: Create localhost plot data directory
  hosts: localhost
  roles:
    - { role: plot-init }
  # tags: floating-point-operation-sine

- name: Deploy openfaas application
  hosts: cloudmaster
  roles:
    - { role: deploy-openfaas-app }
  # tags: floating-point-operation-sine

- name: Start openfaas application resource metrics
  hosts: cloudworker
  roles:
    - { role: resource-metrics }
  # tags: floating-point-operation-sine

- name: Trigger openfaas application
  hosts: cloudmaster
  roles:
    - { role: trigger-openfaas-app }
  # tags: floating-point-operation-sine

- name: Kill the resource metrics script
  hosts: cloudworker
  roles:
    - { role: kill-resource-metrics }
  # tags: floating-point-operation-sine

- name: Get pod logs
  hosts: cloudmaster
  roles:
    - { role: response-log }
  # tags: floating-point-operation-sine

- name: Clean plot data
  hosts: localhost
  roles:
    - {role: plot }
  # tags: floating-point-operation-sine