---
- name: Pause 10 seconds to collect
  ansible.builtin.pause:
    seconds: 10

- name: Kill collect metrics script
  shell: ps aux | grep collect-metrics.sh | grep /bin/sh | awk '{print $2}' | xargs kill -9
  ignore_errors: true
  failed_when: false

  
