---
- name: Pause 10 seconds to collect
  ansible.builtin.pause:
    seconds: 10

- name: Kill collect metrics script
  # shell: ps aux | grep collect-metrics.sh | grep /bin/sh | awk '{print $2}' | xargs kill -9
  shell: ps x | grep "docker stats" | awk '{print $1}' | xargs kill -9
  ignore_errors: true
  failed_when: false
  args:
    executable: /bin/bash

- name: Fetch resource metrics from workers
  fetch:
    src: ~/{{ appName }}-{{ ansible_user }}
    dest: "{{ role_path }}/../plot/files/data/{{ plot_subpath }}/{{ appName }}/r{{ request_concurrent }}pod{{ pod_no }}/resource/"
    flat: true