version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  floating-point-operation-sine:
    lang: python3-debian
    handler: ./floating-point-operation-sine
    image: nightmare224/floating-point-operation-sine:latest
    environment:
      read_timeout: "5m5s"
      write_timeout: "5m5s"
      exec_timeout: "5m5s"
    labels:
      com.openfaas.scale.min: 1
  sorter:
    lang: dockerfile
    handler: ./sorter
    image: nightmare224/sorter:latest
    environment:
        read_timeout: "5m5s"
        write_timeout: "5m5s"
        exec_timeout: "5m5s"
  dd-cmd: 
    lang: python3-debian
    handler: ./dd-cmd
    image: nightmare224/dd-cmd:latest
    limits:
      memory: 3072Mi
      cpu: 4000m
    requests:
      memory: 0Mi
      cpu: 0m
    environment:
      read_timeout: "5m5s"
      write_timeout: "5m5s"
      exec_timeout: "5m5s"
    labels:
      com.openfaas.scale.min: 1
  matrix-multiplication-low:
    lang: python3-debian
    handler: ./matrix-multiplication-low
    image: nightmare224/matrix-multiplication-low:latest
    limits:
      memory: 3072Mi
      cpu: 4000m
    requests:
      memory: 0Mi
      cpu: 0m
    environment:
      read_timeout: "5m5s"
      write_timeout: "5m5s"
      exec_timeout: "5m5s"
    labels:
      com.openfaas.scale.min: 1
  fast-fourier-transform:
    lang: python3-debian
    handler: ./fast-fourier-transform
    image: nightmare224/fast-fourier-transform:latest
    limits:
      memory: 3072Mi
      cpu: 4000m
    requests:
      memory: 0Mi
      cpu: 0m
    environment:
      read_timeout: "5m5s"
      write_timeout: "5m5s"
      exec_timeout: "5m5s"
    labels:
      com.openfaas.scale.min: 1