version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  floating-point-operation-sine:
    lang: python3-debian
    handler: ./floating-point-operation-sine
    image: <DOCKERUSER>/floating-point-operation-sine:latest
    environment:
      read_timeout: 0
      write_timeout: 0
      exec_timeout: 0
    limits:
      memory: 3072Mi
      cpu: 4000m
    requests:
      memory: 0Mi
      cpu: 0m
    labels:
      com.openfaas.scale.min: 1
  sorter:
    lang: dockerfile
    handler: ./sorter
    image: <DOCKERUSER>/sorter:latest
    environment:
        read_timeout: 0
        write_timeout: 0
        exec_timeout: 0
    limits:
      memory: 3072Mi
      cpu: 4000m
    requests:
      memory: 0Mi
      cpu: 0m
  dd-cmd: 
    lang: python3-debian
    handler: ./dd-cmd
    image: <DOCKERUSER>/dd-cmd:latest
    environment:
      read_timeout: 0
      write_timeout: 0
      exec_timeout: 0
    labels:
      com.openfaas.scale.min: 1
    limits:
      memory: 3072Mi
      cpu: 4000m
    requests:
      memory: 0Mi
      cpu: 0m
  matrix-multiplication-low:
    lang: python3-debian
    handler: ./matrix-multiplication-low
    image: <DOCKERUSER>/matrix-multiplication-low:latest
    environment:
      read_timeout: 0
      write_timeout: 0
      exec_timeout: 0
    labels:
      com.openfaas.scale.min: 1
    limits:
      memory: 3072Mi
      cpu: 4000m
    requests:
      memory: 0Mi
      cpu: 0m
  fast-fourier-transform:
    lang: python3-debian
    handler: ./fast-fourier-transform
    image: <DOCKERUSER>/fast-fourier-transform:latest
    environment:
      read_timeout: 0
      write_timeout: 0
      exec_timeout: 0
    labels:
      com.openfaas.scale.min: 1
    limits:
      memory: 3072Mi
      cpu: 4000m
    requests:
      memory: 0Mi
      cpu: 0m