---
- name: Prepare plot data
  shell: |
    cd {{ role_path }}/files/data/{{ appName }}/pod{{ pod_no}}/log/
    tar -xf log-{{ appName }}.tar && rm -f log-{{ appName }}.tar
    cd {{ role_path }}/files/data/{{ appName }}/pod{{ pod_no}}/resource
    cat {{ appName }}* | awk 'NF==3{print}' | sort | uniq > out
    rm {{ role_path }}/files/data/{{ appName }}/pod{{ pod_no}}/resource/{{ appName }}*
