---
- name: OpenFaas port forward
  command: nohup kubectl port-forward -n openfaas svc/gateway 8080:8080 &

- name: Login openfaas
  shell: |
    PASSWORD=$(kubectl get secret -n openfaas basic-auth -o jsonpath="{.data.basic-auth-password}" | base64 --decode; echo)
    echo -n $PASSWORD | faas-cli login --username admin --password-stdin
  args:
    executable: /bin/bash

- name: Login docker
  shell: docker login -u {{ docker_username }} -p {{ docker_password }}

- name: Install hey packet
  become: yes
  apt:
    update_cache: yes
    name: hey