---
- name: Output pod log file
  shell: |
    podname={{ appName }}
    request_concurrent={{ request_concurrent }}
    arr=(`kubectl get pod -n openfaas-fn | sed -n "s/\(${podname}-[^ ]*\)\(.*\)/\1/gp" | tr '\n' ' '`)
    podno=`echo ${arr[@]} | wc -w`
    filepath=result/${podname}/r${request_concurrent}pod${podno}
    mkdir -p ${filepath}
    rm -f ${filepath}/*
    for pod in ${arr[@]}; do kubectl logs -n openfaas-fn ${pod} > ${filepath}/${pod}; done
    cd ${filepath} && tar -cf log-${podname}.tar * && mv log-${podname}.tar ~/
  args:
    executable: /bin/bash

  
- name: Send back to localhost
  fetch:
    src: log-{{ appName }}.tar
    dest: "{{ role_path }}/../plot/files/data/{{ plot_subpath }}/{{ appName }}/r{{ request_concurrent }}pod{{ pod_no }}/log/"
    flat: yes

- name: remove tar file
  shell: rm -f log-{{ appName }}.tar
  args:
    executable: /bin/bash